---
# COPY and this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: <`rake newkey:db`>
  MSG_KEY: <`rake newkey:msg`>
  SECURE_SCHEME: HTTP

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: <`rake newkey:db`>
  MSG_KEY: <`rake newkey:msg`>
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newke:msg` to generate a secret key>
  SECURE_SCHEME: HTTPS
